version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '12.22'
      - node/install-packages
      - run:
          command: npm run test
  deploy-to-staging:
    description: Deploy application to staging server
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '18.12'
      - node/install-packages
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          command: vercel --prod --build-env --name $VERCEL_PROJECT_NAME --scope $VERCER_SCOPE --token=$VERCEL_TOKEN --yes
  
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
                - develop
                - chore/94-set-up-ci
  deploy-to-staging:
    jobs:
      - test:
          filters:
            branches:
              only: chore/94-set-up-ci
      - deploy-to-staging:
          requires:
            - test
  deploy-to-live:
    jobs:
      - test:
          filters:
            branches:
              only: main
      # - deploy-to-live:
      #     requires:
      #       - test
